version: "3"
services:
    web-grooty:
        image: nginx:alpine
        ports:
            - "8080:80"
        volumes:
            - ./grooty:/code
            - ./grooty.conf:/etc/nginx/conf.d/site.conf
        command: /bin/sh -c "rm -f /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
        links:
            - php
        networks:
            - code-network
        depends_on:
            - php
    php:
        image: php:7-fpm-alpine
        volumes:
            - ./grooty:/code
        networks:
            - code-network
        depends_on: 
            - mysql
    mysql:
        image: mysql
        volumes:
            - mysql:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: shaaman
        networks: 
            - code-network

volumes:
    mysql:

networks:
    code-network:
        driver: bridge
