version: "3"

services:
    grooty-web:
        build:
            context: ./grooty/
            dockerfile: nginx.Dockerfile
        ports:
            - "8082:80"
        volumes:
            - ./grooty:/code
            - ./grooty/grooty.nginx.conf:/etc/nginx/conf.d/site.conf
            - templates-grooty:/tmp/twig/grooty
        links:
            - grooty-php
        networks:
            - grooty-network
        depends_on:
            - grooty-mysql
            - grooty-php

    grooty-php:
        build:
            context: ./grooty/
            dockerfile: php-fpm.Dockerfile
        volumes:
            - ./grooty/:/code
            - templates-grooty:/tmp/twig/grooty
        command: /bin/sh -c "cd /code && composer install && php-fpm"
        networks:
            - grooty-network
        depends_on:
            - grooty-mysql

    grooty-mysql:
        build:
            context: ./grooty/
            dockerfile: mysql.Dockerfile
        volumes:
            - ./grooty/scripts/db:/scripts
            - mysql-grooty:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=shaaman
            - MYSQL_DATABASE=grooty
            - MYSQL_USER=grooty
            - MYSQL_PASSWORD=grooty
        networks:
            - grooty-network

    site-web:
        build:
            context: ./site/
            dockerfile: nginx.Dockerfile
        ports:
            - "8081:80"
        volumes:
            - ./site/:/code
            - ./site/site.nginx.conf:/etc/nginx/conf.d/site.conf
            - templates-site:/tmp/twig/site
        links:
            - site-php
        networks:
            - site-network
        depends_on:
            - site-mysql
            - site-php

    site-php:
        build:
            context: ./site/
            dockerfile: php-fpm.Dockerfile
        volumes:
            - ./site/:/code
            - templates-site:/tmp/twig/site
        command: /bin/sh -c "cd /code && composer install && php-fpm"
        networks:
            - site-network
        depends_on:
            - site-mysql

    site-mysql:
        build:
            context: ./site/
            dockerfile: mysql.Dockerfile
        volumes:
            - mysql-site:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=shaaman
            - MYSQL_DATABASE=site
            - MYSQL_USER=site
            - MYSQL_PASSWORD=site
        networks:
            - site-network


volumes:
    mysql-grooty:
    mysql-site:
    templates-grooty:
    templates-site:

networks:
    grooty-network:
        driver: bridge
    site-network:
        driver: bridge
